theme: jekyll-theme-minimal

title: Matthew Nokleby
logo: me.jpg
description: Principal Scientist @ Best Buy. Former Director AI Science @ Target, professor of ECE @ Wayne State, alum of iiD @ Duke and ECE @ Rice. Working in machine/deep learning, computer vision, and NLP.