theme: jekyll-theme-minimal

title: Matthew Nokleby
logo: me.jpg
description: Director AI Science @ Target. Former professor of ECE @ Wayne State, alum of iiD @ Duke and ECE @ Rice. Working in machine/deep learning and computer vision.