theme: jekyll-theme-minimal

title: Matthew Nokleby
logo: me.jpg
description: Computer Vision Lead @ Lily AI. Former Director AI Science @ Target, Principal Scientist @ Best Buy, professor of ECE @ Wayne State, alum of iiD @ Duke and ECE @ Rice. Working in machine/deep learning, computer vision, and NLP.